version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  db-data: