spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    validate-migration-naming: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: dev

app:
  description: "This API exposes endpoints to manage users."
  version: "v1.0"
  minimum-age: 18
  jwt:
    minutes: 60
    days: 30
    secret:
      access: "qBTmv4oXFFR2GwjexDJ3t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
      refresh: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s1J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="

springdoc:
  swagger-ui:
    path: /swagger-ui